### PR TITLE
Added list of APNs for convenience.

### PR DESCRIPTION
**Pull request by justindriggers**

### CODE REVIEW

**Comment by crpalmer** [comment]
Why?  We are pulling in the cm apns which is the list that is being actively maintained by cm developers.

**Comment by justindriggers** [comment]
I suppose the CM APNs don't include AT&T's nxtgenphone, so I've been having to manually add it and activate after completing the setup process on wifi.

**Comment by crpalmer** [comment]
You should try adding the appropriate APNs (just the ones that you need, not all of them!) to the apn list in vendor/cm and then submit that change up via gerrit and then everyone can get them.

**Comment by justindriggers** [comment]
Good call. I'll kill this PR

**Pull request closed without merging**
